---
- name: updating nginx server_name
  lineinfile: dest={{ nginx_ghost_conf }} state=present regexp='server_name .*' line='server_name {{ hostname }};'
  notify: restart nginx

- name: updating ghost url
  lineinfile: dest={{ ghost_conf }} state=present regexp='http://my-ghost-blog.com' line={{ url_line }}
  notify: restart ghost

- name: updating ghost mail
  lineinfile: dest={{ ghost_conf }} state=present regexp={{ mail_regexp }} line={{ mail }}
  notify: restart ghost
  when: mail_user is defined and mail_pass is defined
